name: Continuous Integration with GitHub, GitHub Actions and Docker Hub

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Log in to Docker Hub
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Docker Compose Build
       working-directory: ./ASP.NET-8
       run: docker compose build

     - name: Push to Docker Hub Container Registry
       run: |
         docker tag docker-from-zero-to-mastery-dotnet-8:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8:latest
         docker tag docker-from-zero-to-mastery-dotnet-8:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8:${{ github.run_id }}
         
         docker tag mysql:8.0.29 ${{ secrets.DOCKER_USERNAME }}/mysql:8.0.29
         docker tag mysql:8.0.29 ${{ secrets.DOCKER_USERNAME }}/mysql:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/mysql:8.0.29
         docker push ${{ secrets.DOCKER_USERNAME }}/mysql:${{ github.run_id }}
